// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqACkLsQyN1UOoD-P_ppn1Nehy8A73T2s',
    appId: '1:330822604002:web:2b2718e390cd520bf3babb',
    messagingSenderId: '330822604002',
    projectId: 'lingobreeze-31b26',
    authDomain: 'lingobreeze-31b26.firebaseapp.com',
    storageBucket: 'lingobreeze-31b26.firebasestorage.app',
    measurementId: 'G-NZKYF453PB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSh1c1tjso2R30MwUeaUuKEtF8dw6Oxx0',
    appId: '1:330822604002:android:aed869d3483c4545f3babb',
    messagingSenderId: '330822604002',
    projectId: 'lingobreeze-31b26',
    storageBucket: 'lingobreeze-31b26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlxA7YQz6iqV72IcFDBoE34fjghtk2B4E',
    appId: '1:330822604002:ios:6185c406b5ece689f3babb',
    messagingSenderId: '330822604002',
    projectId: 'lingobreeze-31b26',
    storageBucket: 'lingobreeze-31b26.firebasestorage.app',
    iosBundleId: 'com.example.lingobrezze',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlxA7YQz6iqV72IcFDBoE34fjghtk2B4E',
    appId: '1:330822604002:ios:6185c406b5ece689f3babb',
    messagingSenderId: '330822604002',
    projectId: 'lingobreeze-31b26',
    storageBucket: 'lingobreeze-31b26.firebasestorage.app',
    iosBundleId: 'com.example.lingobrezze',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqACkLsQyN1UOoD-P_ppn1Nehy8A73T2s',
    appId: '1:330822604002:web:5a5ddca21914091ef3babb',
    messagingSenderId: '330822604002',
    projectId: 'lingobreeze-31b26',
    authDomain: 'lingobreeze-31b26.firebaseapp.com',
    storageBucket: 'lingobreeze-31b26.firebasestorage.app',
    measurementId: 'G-BLD1YKBV78',
  );
}
